name: Nexus
main: me.pugabyte.nexus.Nexus
version: ${project.version}
api-version: "1.16"
softdepend:
  - BlueMap
  - BuycraftX
  - Citizens
  - Essentials
  - helper
  - HolographicDisplays
  - LiteBans
  - LWC
  - mcMMO
  - Multiverse-Core
  - Multiverse-Inventories
  - NBTAPI
  - NoteBlockAPI
  - PremiumVanish
  - ProtocolLib
  - SmartInvs
  - Vault
  - Votifier
  - WorldGuard
  - WorldGuardRegionAPI
