name: Nexus
main: me.pugabyte.nexus.Nexus
version: ${project.version}
api-version: 1.16
load: POSTWORLD
depend:
  - Multiverse-Core
softdepend:
  - BentoBox
  - BlueMap
  - BuycraftX
  - Citizens
  - GlowAPI
  - helper
  - HolographicDisplays
  - LibsDisguises
  - LWC
  - mcMMO
  - Multiverse-Inventories
  - NBTAPI
  - NoteBlockAPI
  - PremiumVanish
  - ProtocolLib
  - SmartInvs
  - Vault
  - Votifier
  - WorldGuard
